<? # $Id: ARMOR_UP.action,v 1.00 2022-11-04 22:30:00 Elempher $

// действие "Улучшить снаряжение --> замена артикула предмета с сохранением всех вставок и настроек."
// Параметры:
//	$in['artifact_id'] - артефакт который нужно апнуть

if (!in_array($subject['object_class'],array(OBJECT_CLASS_USER))) return;
if (!in_array($object['object_class'],array(OBJECT_CLASS_ARTIFACT))) return;
if (($subject['flags'] & USER_FLAG_NOACTION) || $subject['fight_id'] || $subject['trade_sess_id']) {
    $out['error'] = translate('В настоящий момент это действие выполнить нельзя!');
    return;
}
$artifact_id = intval($in['artifact_id']);
$artifact = $artifact_id ? artifact_get(array('id' => $artifact_id, 'user_id' => $subject['id'],)) : false;
$artikul = artifact_artikul_get($artifact['artikul_id']);

if (!($artifact['flags2'] = ARTIFACT_FLAG2_LEGENDARY)) { // не даст апнуть нелегендарный предмет
    $out['error'] = translate('Нужно выбрать легендарный предмет!');
    return;
}

$armor_up = artifact_artikul_get($object['artikul_id']);
if (!$armor_up || ($armor_up['param1'] == -1 || $armor_up['param1'] > 0)) {
    $out['error'] = translate('Невозможно выполнить действие!');
    return;
}

$next_up = artifact_artikul_get(array('id' => $artifact['param1'],));

artifact_save(array(
    'id' => $artifact['id'],
	'artikul_id' => $artifact['param1'],
	'param1' => $next_up['param1'],
));
$out['status'] = ACTION_STATUS_OK;

if($armor_up['param1'] == -1) {
    chat_msg_send_system('Артикул артефарта:  "'.$artikul['title'].'" удален!', CHAT_CHF_USER, $subject['id']);
}else{
    chat_msg_send_system('<b>Вы улучшили легендарное снаряжение: "'.$artikul['title'].'"!</b>', CHAT_CHF_USER, $subject['id']);
}

