<?php 

if (!$action['param1']) return;
if (!in_array($subject['object_class'],array(OBJECT_CLASS_USER))) return;

$rand_seed = intval(microtime(1)*1000);

srand($rand_seed);	
$bonus_out = bonus_apply($real_user, $action['param1']);
if ($bonus_out['status'] == BONUS_STATUS_OK) {
	$out['status'] = ACTION_STATUS_OK;
	srand($rand_seed);	
}
