<? # $Id: ENCHANT2.action,v 1.5 2010-01-15 09:50:11 p.knoblokh Exp $

// действие "наложить руну"
// Параметры:
//	$in['artifact_id'] - артефакт на который нужно наложить руну

global $user_body_slots;

if (!in_array($subject['object_class'],array(OBJECT_CLASS_USER))) return;
if (!in_array($object['object_class'],array(OBJECT_CLASS_ARTIFACT))) return;
if (($subject['flags'] & USER_FLAG_NOACTION) || $subject['fight_id'] || $subject['trade_sess_id']) {
	$out['error'] = translate('В настоящий момент это действие выполнить нельзя!');
	return;
}
$artifact_id = intval($in['artifact_id']);
$artifact = $artifact_id ? artifact_get(array('id' => $artifact_id, 'user_id' => $subject['id'])) : false;

if (!$artifact || $artifact['slot_id']) { // неверный или одетый предмет
	$out['error'] = translate('Нужно выбрать предмет в который вставляется руна!');
	return;
}

if ($artifact['flags'] & ARTIFACT_FLAG_ARMOR_STYLE) {
	$out['error'] = translate('Нельзя зачаровать этот предмет!');
	return;
}

if (($artifact['enchant2_id'] > 0)) {
	action_object_delete(OBJECT_CLASS_ARTIFACT, $artifact);
}elseif (($artifact['flags'] & ARTIFACT_FLAG_USE)) {
	$out['error'] = translate('На предмет уже наложено действие!');
	return;
}

$enchant = $object['param1'] ? artifact_artikul_get($object['param1']) : false;
if (!$enchant || !$enchant['kind_id']) {
	$out['error'] = translate('Невозможно выполнить действие!');
	return;
}

$artifact_artikul = artifact_artikul_get($artifact['artikul_id']);
if (!in_array($artifact_artikul['slot_id'], $user_body_slots)) {
	$out['error'] = translate('Невозможно наложить руну на этот предмет!');
	return;
}

artifact_save(array(
	'id' => $artifact['id'],
	'enchant2_id' => $enchant['id'],
	'artikul_actions' => 1,
	'_set' => sql_pholder(' flags = flags | ? ', ($enchant['flags'] & ARTIFACT_FLAG_EXTERNAL) ? (ARTIFACT_FLAG_USE | ARTIFACT_FLAG_EXTERNAL) : ARTIFACT_FLAG_USE),
));
require_once('lib/user_stat.lib');	
require_once('lib/chat.lib');	
user_stat_update($subject['id'], USER_STAT_TYPE_SKILL, USER_STAT_SKILL_REP_KUSYA, 5);
chat_msg_send_system('<b>Вы получили <b style="color:darkred;">5 репутации Кузнеца</b></b>', CHAT_CHF_USER, $subject['id']);
$out['status'] = ACTION_STATUS_OK;

artifact_artikul_get_title($artifact, array($artifact_artikul['id'] => $artifact_artikul));
// лог-сервис -----------------------
logserv_log_action(array(
	'action' => $action,
	'comment' => sprintf(translate('Наложена руна на "%s"'),$artifact['title']),
),$action_user);
// ----------------------------------

?>
